### ISSUE TITLE
Missing configmap values?

### ISSUE THREAD

**Issue by Streppel** [sethvargo/vault-kubernetes-workshop#10]
This is more of a doubt, but we declare configmap vault to have values

```
    --from-literal "load_balancer_address=${LB_IP}" \
    --from-literal "gcs_bucket_name=${GCS_BUCKET}" \
    --from-literal "kms_key_id=${KMS_KEY}"
```

but on vault deployment file we use many other values

```
env:
        - name: GCS_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: vault
              key: gcs_bucket_name
        - name: KMS_PROJECT
          valueFrom:
            configMapKeyRef:
              name: vault
              key: kms_project
        - name: KMS_REGION
          valueFrom:
            configMapKeyRef:
              name: vault
              key: kms_region
        - name: KMS_KEY_RING
          valueFrom:
            configMapKeyRef:
              name: vault
              key: kms_key_ring
        - name: KMS_CRYPTO_KEY
          valueFrom:
            configMapKeyRef:
              name: vault
              key: kms_crypto_key
        - name: LOAD_BALANCER_ADDR
          valueFrom:
            configMapKeyRef:
              name: vault
              key: load_balancer_address
```

Aren't we missing some values here? I'm asking this because my pods are failing to deploy because of this:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2300328/59859938-1461cb00-9354-11e9-9beb-a11ab9b0f87e.png">
